version: "3.7"

services: 
    mongo:
        container_name: mongo
        image: mongo
        restart: always

        volumes:
            ['/private/var/services/mongodb:/data/db']

        ports:
            - '27017:27017'
    api:
        container_name: api
        tty: true
        stdin_open: true
        restart: always
        build:
            context: api
            dockerfile: Dockerfile
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - '3001:3001'
        volumes:
            - './api:/api'
            - '/api/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - dev=false
    app:
        container_name: app
        tty: true
        stdin_open: true
        restart: always
        build:
            context: app
            dockerfile: Dockerfile
        depends_on:
            - api
        links:
            - api
        volumes:
            - './app:/app'
            - '/app/node_modules'
        ports:
            - '3005:3005'
        command:
            'yarn dev'
