version: "3.7"

services: 
    mongo:
        container_name: mongo
        image: mongo
        restart: always

        volumes:
            ['/private/var/services/mongodb:/data/db']

        ports:
            - '27017:27017'
    api:
        build:
            context: api
            dockerfile: Dockerfile
        tty: true
        stdin_open: true
        restart: always
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - '3001:3001'
        volumes:
            - './api:/api'
            - '/api/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true

